# Generated by Django 5.2.1 on 2025-06-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_workout_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
