# Generated by Django 5.2.1 on 2025-06-20 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_workoutexercise_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutexercise',
            name='sets',
        ),
    ]
