# Generated by Django 5.2.1 on 2025-08-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_remove_workoutexercise_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycleday',
            name='default_exercises',
            field=models.ManyToManyField(blank=True, to='bot.exercise'),
        ),
    ]
