# Generated by Django 5.2.1 on 2025-11-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_cycleday_default_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycleday',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
