# Generated by Django 5.2.1 on 2025-12-06 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_cycleday_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='cycle_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workouts', to='bot.cycleday'),
        ),
    ]
